name: Push package

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  NUGET_USER: ${{ secrets.NUGET_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Pack
      run: dotnet pack --configuration Release -o "./packages" src/Enrichment
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source --username "$GITHUB_ACTOR" --password "$GITHUB_TOKEN" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Drenalol/index.json"
        dotnet nuget push "./packages/*.nupkg" --source github --skip-duplicate
    - name: NuGet login (OIDC -> temp API key)
      if: env.NUGET_USER != ''
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: Publish NuGet
      if: env.NUGET_USER != ''
      run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
